[package]
name = "bootloader"
version = "0.10.10"
authors = ["Philipp Oppermann <dev@phil-opp.com>"]
license = "MIT/Apache-2.0"
description = "An experimental x86_64 bootloader that works on both BIOS and UEFI systems."
repository = "https://github.com/rust-osdev/bootloader"
edition = "2021"

[workspace]
members = [
    "api",
    "common",
    "uefi",
    "bios",
    "bios/first_stage",
    "tests/runner",
    "tests/test_kernels/default_settings",
    "tests/test_kernels/map_phys_mem",
    "tests/test_kernels/higher_half",
]
exclude = ["examples/basic", "examples/test_framework"]


[dependencies]
argh = "0.1.3"
displaydoc = "0.1.7"
anyhow = "1.0.32"
llvm-tools = "0.1.1"
thiserror = "1.0.20"
json = "0.12.4"
fatfs = "0.3.4"
gpt = "3.0.0"

[build-dependencies]
llvm-tools-build = { version = "0.1", optional = true, package = "llvm-tools" }
toml = { version = "0.5.1", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
quote = { version = "1.0", optional = true }
proc-macro2 = { version = "1.0", optional = true }


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = false
debug = true
overflow-checks = true

[profile.first-stage]
inherits = "release"
opt-level = "s"
lto = true
codegen-units = 1
debug = false
overflow-checks = false


[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"

[package.metadata.release]
no-dev-version = true
pre-release-replacements = [
    { file = "Changelog.md", search = "# Unreleased", replace = "# Unreleased\n\n# {{version}} – {{date}}", exactly = 1 },
]
pre-release-commit-message = "Release version {{version}}"
