[package]
name = "bootloader"
version = "0.11.0-alpha.0"
authors = ["Philipp Oppermann <dev@phil-opp.com>"]
license = "MIT/Apache-2.0"
description = "An experimental x86_64 bootloader that works on both BIOS and UEFI systems."
repository = "https://github.com/rust-osdev/bootloader"
edition = "2021"

[workspace]
members = [
    "api",
    "common",
    "uefi",
    "bios",
    "bios/first_stage",
    "tests/runner",
    "tests/test_kernels/default_settings",
    "tests/test_kernels/map_phys_mem",
    "tests/test_kernels/higher_half",
    "tests/test_kernels/pie",
]
exclude = ["examples/basic", "examples/test_framework"]


[dependencies]
anyhow = "1.0.32"
fatfs = "0.3.4"
gpt = "3.0.0"
raw-cpuid = { version = "10.2.0", optional = true }
rand = { version = "0.8.4", optional = true, default-features = false }
rand_chacha = { version = "0.3.1", optional = true, default-features = false }

# [dependencies.bootloader-x86_64-uefi]
# version = "0.1.0"
# path = "uefi"
# artifact = ["bin"]
# target = "x86_64-unknown-uefi"


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = false
debug = true
overflow-checks = true

[profile.first-stage]
inherits = "release"
opt-level = "s"
lto = true
codegen-units = 1
debug = false
overflow-checks = false


[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"

[package.metadata.release]
no-dev-version = true
pre-release-replacements = [
    { file = "Changelog.md", search = "# Unreleased", replace = "# Unreleased\n\n# {{version}} – {{date}}", exactly = 1 },
]
pre-release-commit-message = "Release version {{version}}"
