[package]
name = "uefi-test"
version = "0.1.0"
authors = ["Philipp Oppermann <dev@phil-opp.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uefi = "0.4.4"
rlibc = "1.0.0"
uefi-services = "0.2.4"
log = "0.4.8"
