[build]
target = "x86_64-bootloader.json"

[target.x86_64-unknown-uefi]
runner = "cargo run --manifest-path runner/Cargo.toml --target x86_64-unknown-linux-gnu"

[alias]
x = "-Z build-std=core,alloc"
